version: 0.0
os: linux
files:
  - source: /
    destination: /ubuntu/home/
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: /scripts/before_install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: /scripts/install_dependencies.sh
      timeout: 120
      runas: ubuntu

  ApplicationStart:
    - location: /scripts/application_start.sh
      timeout: 300
      runas: ubuntu
