version: 0.0
os: linux
files:
  - source: /
    destination: /ubuntu/home/server
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: /scripts/install_dependencies.sh
      timeout: 120
      runas: ubuntu
